services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: database
    ports:
      - "27017:27017"
    volumes:
      - mongo-test-data:/data/db

volumes:
  mongo-test-data: